services:
  - type: worker
    name: felix-activity-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python FelixActivityBot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/activity_tracker.db